### ISSUE TITLE
Add support for Emoji in Bot commands

### ISSUE THREAD

**Issue by lchi** [venmo/slouch#1]
I'd like to add support for emoji in bot commands. This would allow bots to receive messages likes `bot: :scissors:`.

One idea for implementation is to have the `command` decorator take in optional arguments, so you could write the following:

```
@Bot.command(name=':scissors:')
def scissors():
     ....
```

Thoughts?

**Comment by simon-weber** [comment]
Sounds reasonable to me :+1:

**Comment by simon-weber** [comment]
Probably want to decorate the decorator to keep no-arg support. This is what we use in vcrutils:

```python
def dual_decorator(func):
    """This is a decorator that converts a paramaterized decorator for no-param use.
    source: http://stackoverflow.com/questions/3888158
    """

    @wraps(func)
    def inner(*args, **kw):
        if ((len(args) == 1 and not kw and callable(args[0])
             and not (type(args[0]) == type and issubclass(args[0], BaseException)))):
            return func()(args[0])
        else:
            return func(*args, **kw)
    return inner
```

**Comment by lchi** [comment]
Cool, I'll post a PR when ready.
